title: "Coding In The Open"
baseURL: "https://codingedi.github.io"
languageCode: "en-GB"
theme: "osprey-delight"
tags: ["homepage", "portfolio", "event"]
#canonifyURLS: true
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
pygmentsUseClasses: true

## Generic theme parameters:
Params:
  author: "codingEDI"
  description: "Coding In The Open - talks on working openly"

  # logoBig appears at the top of the page. Use a path relative to the assets dir for auto-resizing. 
  logoBig: "cito-page.png"

  # logoSmall is the logo that will be shown in the left corner of the nav bar.
  #   Use a path relative to the assets dir for auto-resizing.
  logoSmall: "favicon.png"

  # tagline (followed by a cursor) is shown at the top, below the logo
  #tagline: "Welcome!"

  # mdTagline can be used instead to specify the tagline in Markdown for more customizability.
  #   Note that {cursor} is a placeholder and will be replaced by the actual cursor HTML when rendering.
  mdTagline: "# A week of lunchtime talks on working with open principles\n## 1-2pm 14-18th June 2021\n\nWant to know more? Come and *[chat with us on Matrix](https://matrix.to/#/!zXuezsmKutfOJtgTZv:matrix.org)!*"
  favicon: "favicon.png"

  opengraphImage: "/homelogo-300.png"

  # enforceSinglePage will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html'. This file will contain only a redirect directive if this switch is enabled.
  enforceSinglePage: true

  # copyright flag generates a copyright notice in footer for your site.
  copyright: true

## Social links in footer:
  Social:
  - type: info # the icon to use. can be anything mentioned in "assets/sass/_icons.scss" 
    url: "https://matrix.to/#/!zXuezsmKutfOJtgTZv:matrix.org"


## Theme features:
  Feat:
    # useLazySizes to lazy load images with lazysizes (recommended)
    useLazySizes: true

    # useStructuredData for your own https://schema.org/Person (SEO-friendly).
    #   This will be auto-generated dependent on the information you provide in this configuration.
    useStructuredData: false

    # structuredDataGitHubUser needs your USERNAME so that the GitHub API is used to fetch more information for structured data.
    #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
    #structuredDataGitHubUser = "USERNAME"

    # useTermynal enables Termynal (https://github.com/ines/termynal), a small JS library for showing a terminal "animation" from within your gallery item.
    #   The cool thing is that the library has been stripped-down to a minimum to only have the necessary functionality.
    useTermynal: true

    googleTagManager: ""
  
  # Expert mode: Configure image resizing (some of the settings are not yet publicly documented)
  Image:
    Logo:
      resize: "300x"

    Gallery:
      resize: "400x"

    # Background:
    #   resize: "1920x"
      

## The menu items are automatically added to navbar. Use content files for more advanced usage.
##   See: https://gohugo.io/content-management/menus/#add-content-to-menus
Menu:
  Main:
    - name: "About"
      identifier: about
      url: "/#about"
      weight: 1
    - name: "Speakers"
      identifier: gallery
      url: "/#speakers"
      weight: 2
    - name: "Schedule"
      url: "/#schedule"
      identifier: schedule
      weight: 3
    - name: "Organisers"
      url: "/#organisers"
      identifier: organiser
      weight: 4
    - name: "Conduct"
      url: "/#coc"
      identifier: coc
      weight: 5
